# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rgammatr <- function(a, b, range, n = 1) {
    .Call(`_fBN_rgammatr`, a, b, range, n)
}

checkDAG <- function(G) {
    .Call(`_fBN_checkDAG`, G)
}

get_zcoef <- function(xobs, zobs, scoef, sbasis, fscore, eta, svar, tindex, cindex, findex) {
    .Call(`_fBN_get_zcoef`, xobs, zobs, scoef, sbasis, fscore, eta, svar, tindex, cindex, findex)
}

get_scoef <- function(xobs, zobs, zcoef, scoef, sbasis, penat, fscore, svar, lambda, tindex, cindex, findex, orderLambdas = 1L) {
    .Call(`_fBN_get_scoef`, xobs, zobs, zcoef, scoef, sbasis, penat, fscore, svar, lambda, tindex, cindex, findex, orderLambdas)
}

rcpparma_hello_world <- function() {
    .Call(`_fBN_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_fBN_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_fBN_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_fBN_rcpparma_bothproducts`, x)
}

